name: Release

on:
  push:
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    strategy:
      matrix:
        terraform: [0.12.31, 0.13.7, 0.14.11, 0.15.5, 1.0.11, 1.1.9, 1.2.9, 1.3.8]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Terraform Format'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
      
      - run: |
          terraform fmt
          terraform init

      - name: 'Inject provider configs for validate command'
        run: |
            cat > providers.tf <<EOF
            provider "aws" {
              region = "us-east-2"
            }
            EOF

      - run : |
          terraform validate

  release:
    if: github.event_name == 'push'
    needs: terraform
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        semantic_version: 19
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git

